### ISSUE TITLE
Last version does not send traces to jaeger properly

### ISSUE THREAD

**Issue by JasterV** [primait/prima_tracing.rs#89]
So, I updated to the last 0.8.1 version and suddendly I could not see my traces locally. 
I tried to update jaeger or downgrade it and nothing.
Then I just went back to the 0.6.0 version of this library and everything worked fine again )):

I have the features `traces` and `datadog` activated

This is how I am using this library:

```
pub fn init(config: TracingConfig) -> prima_tracing::Uninstall {
    let subscriber_config = prima_tracing::builder(&config.service_name)
        .with_env(config.app_env.into())
        .with_country(prima_tracing::Country::Common)
        .with_version(config.version)
        .with_telemetry(config.opentelemetry_url.into(), config.service_name)
        .build();

    let subscriber = prima_tracing::configure_subscriber(subscriber_config);

    prima_tracing::init_subscriber(subscriber)
}
```

This works on 0.6.0 but not on 0.8.1, although no error is reported on the latest version

**Comment by JasterV** [comment]
Update: it works with version 0.7.2 too

**Comment by MaeIsBad** [comment]
We missed this issue, sorry! 
Closing since this has been fixed now
